---
title: "Code Quality and Documentation"
author: "Best Practices for Writing Reproducible Code // part 3"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, 'custom.css']
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Code quality defined

.pull-left[
- Readable (Next part)

- Reusable

- Robust
]

---
# Code robustness (part 1)

- Separate code and data: don't hard code variables!

  - and if you must...
  - Do it once, e.g. weeklength = 7
  - Consider using a config file for project-specific (meta)data!
  
- Don't repeat yourself: use functions

 - Write routines in functions, ie., code you reuse often
 - Change hard coded values by arguments in your functions
 - Identify potential functions by their action: functions perform tasks (e.g. sorting, plotting, saving a file, transform data...)

---
# Functions

Functions are smaller code units reponsible of one task.

- Functions are meant to be reused

- Functions accept arguments (values)

- What arguments a function accept is defined by its parameters

```python
def sort_data(data, how="asc", column=0):
  raise NotImplementedException("Ooops")
  
try:
  sort_data(protein_data)
except Exception as ex:
  logger.log("It went wrong")
```
---
# Code reusability

- Modular code is reusable code

  - One script for one purpose
  - Document clearly what comes in and what comes out
  - When using (adjustable) parameters in your code, use a config file that can be adjusted *outside* of your code

--

- Consider the modularity of your functions
  - Separate functions into generic and specific elements
  - Generic part can and will be reused
  - Specific elements are unique applicable in specific situations

--
  
- Do One Thing (and do it well)
  - One function for one purpose
  - One class for one purpose
  - One script for one purpose (no fishing to recycle it!)

---
# Your turn

Take a look at your code.
- Are you repeating yourself: do you have repeated code that could be a function?

- Can you separate a function into generic and specific elements?

- Is there hard coded data or adjustable parameters that you can extract (perhaps in a config file?)

- Identify a part of your code that you could transform into a function
  - Make sure you function has parameters
  - Use those parameters inside the function
  - Example:
  
```{python}
def my_function(param_a, param_b):
  if param_b == 99:
    return None
  
  if param_a == 100:
    do_something(param_a)
  else:
    do_something_else(param_a)
```


---
# Towards defensive programing

- Error management
 - Check values before processing them
  - Make use of try/catch mechanisms to manage exceptions
  - Make use of logging tools instead of print functions

- *About errors* : Do not expect users to treat your code like you expected, so expect the worst
 - use of wrong input values using your functions
 - data types
 - malformed text input

- Make use of systematic tests
 - Unit testing (event if you work alone on your code)
 - Continuous integration (if many authors work on code)

---
# Error management

- Check values with if/else

```python
if not protein_data:
  raise ValueError("Dataset cannot be empty")
```

- With try catch (called except in Python)

```python
try:
  do_something_that_might_go_wrong(protein_data)
except ItWentWrongException as ex:
  logger.log(ex)
finally:
  protein_data.to_csv("../data/processed/proteins.csv")
```
---

# Your turn
- Modify the code inside your function to
  - Check the value of the arguments passed to your function using if/else statements
  - raise an error in case an argument is out of the range of acceptable values
  - Example (in python)
  
```{python}
def read_vector_value(index=0):
    my_vector = [10,5,4,12,25]
    
    if index > len(my_vector) - 1:
        raise IndexError('Index cannot be higher than length of the vector ')
    
    return my_vector[index]
```
  - Example (in R)
```{R}

```
---
# Using the read_vector_value function
- Good call
```{python}
read_vector_value(4)
```

- Bad call
```{python, error=TRUE}
read_vector_value(5)
```

---
# So, your script gets interrupted by the error your raised
```{python, error=TRUE}
result = read_vector_value(5)
```


```{python, error=TRUE}
result
```

---
# Mmmh... why not a good old if/return?

```{python}
def read_vector_value_if(index=0):
    my_vector = [10,5,4,12,25]
    
    if index > len(my_vector) - 1:
        return None
    
    return my_vector[index]

print(read_vector_value_if())
```

- Hard to know if None is an expected value or an error ...
```{python}
print(read_vector_value_if(55))
```
---
# You can handle this! With some error management

- Assuming you would like to do something else than interrupt your script when an error is raised
- Use error management, you can use it to process errors/exceptions raised by functions

```{python, error=TRUE}

try:
  read_vector_value(5)
except IndexError as e:
  print(e)

```

- But what if the wrong exception is handled?

```{python, error=TRUE}
try:
  read_vector_value(5)
except ArithmeticError as e:
  print(e)
```
---

# Unit testing
Unit testing is a generic testing approach.

Your software is tested by focusing on smaller units, for instance a series of functions or class.

Extra packages\\imports are needed

- in R with the testthat/testthis packages
  - https://github.com/r-lib/testthat, https://github.com/r-lib/testthis
- in python with pytest, unittest
  - https://docs.python.org/3/library/unittest.html 

---
# Running unit tests
__Code editors/IDEs__ such as visual studio code, RStudio, Pycharm...

- Integrate functionalities to run and show the results of unit tests
  - E.g., RStudio in the build menu -> test package
  
1. Create a unittest file
  
  ```R
  usethis::use_test("hello")
  ```
  
2. Edit the file test-hello.R in the tests folder (created by usethis)
  
  ```R
  test_that("multiplication works", {
    expect_equal(2 * 2, 4)
  })
  ```
  
3. Run tests
  - In RStudio using the menu __or__
  ```R
    devtools::test()
  ```
---
# Example, testing our read_vector function

```{python}
import unittest
class TestStringMethods(unittest.TestCase):
    def test_retrieval(self):
        self.assertEqual(read_vector_value(0), 10)
    
    def test_error(self):
        with self.assertRaises(IndexError):
            read_vector_value(5)

```

- Normal call

```{python, eval=FALSE}
unittest.main()
```

---
# With a Jupyter notebook

- Notebook call

```{python}
unittest.main(argv=['trick to make it work in a notebook'], exit=False)
```

---
# Making a test fail
```{python}
import unittest
class TestStringMethods(unittest.TestCase):
    def test_retrieval(self):
        self.assertEqual(read_vector_value(0), 10)
    
    def test_error(self):
        with self.assertRaises(IndexError):
            read_vector_value(5)
            
    def test_retrieval_wrong(self):
        self.assertEqual(read_vector_value(0), 11)

```
---
#Result of faulty test

```{python, echo=FALSE}
unittest.main(argv=['trick to make it work'], exit=False)
```
---
# Your turn
- Write a unit test for your function
- Does your function behave like you want?
- Can you make your function raise unforseen errors/exceptions?
- Inspect R and python documentation to get acquainted with different assertions (e.g., assertEqual)