# Documentation

Documentation is an essential part of software development. It helps you and others understand the code you have written, and how to use it. There are many different types of documentation, and different potential target audiences you might want to address. 

The most important target audience is yourself in a few months time, when you have forgotten the details of what you did. From experience we can tell that having good documentation can make you very happy with yourself (and save a lot of frustration) when you come back to a project after some.

Furthermore, it is important to keep in mind which other people might want to learn about, use or even adapt your code for their own purposes, and what they might need to know to be able to do so.

In this part, we will cover some of the most important types of documentation, and how to structure and write your documentation.

## Chapters:

* [Writing code documentation](comments-and-docstrings.qmd)

* [Writing good README files](readme-files.qmd)



