# Schedule

## Pre-Workshop Installation Support

Please make sure to follow the [preparation instructions] carefully well before the workshop starts. In case you run into issues, check the pre-workshop email that is sent to you one week before the workshop. It will provide instrutions on how to find help.

### Day 1

| Time  | Activity |
|-------:|----------|
| 8:45 | Walk-in and Installation Support |
| 9:15 | [Welcome & introduction](introduction.qmd))| 
| 9:30 | [Project setup & version control with git](project-management.qmd) |
| 10:45 | Questions & discussion |
| _11:00_ | _Break_ |
| 11:15 | [Code quality](code-quality.qmd)  |
| 12:45 | Questions & discussion |
| _13:00_ | _End_ |


### Day 2

| Time  | Activity |
|-------:|----------|
| 9:00 | Code quality discussion | 
| 9:15 | [Documentation](documentation.qmd)  |
| 10:45 | Questions & discussion |
| _11:00_ | _Break_ |
| 11:15 | [Reproducibility](reproducibility.qmd)  |
| 11:45 | [Publishing](publishing.qmd)
| 12:15 | [Reproduction of projects](reproducibility-check.qmd) |
| _13:00_ | _End_ |
