# Your Project

# Data and/or Code

-   **Bring some code!** We will be working on improving your workflow, so it is nice if you bring one of your current (or previous) projects to work with. Consider that we will need something that is small enough that you can edit/play with it during the workshop, but also comprehensive so that someone else may be able to reproduce your project on their computer (i.e.: it is nice if there is an output for someone to see at the end!). For example, if you are working on a project that contains many steps (or a long time) to complete, it could be handy to either reduce the runtime by reducing the problem size, or select parts of your scripts to work on during the workshop. E.g. choose one of your scripts (or copy parts of a script to a new temporary script) that produces a single (or a few) outputs/figures in a couple of minutes maximum by running one (or small number of) script. *NB 1: If you don't know how to simplify/reduce your workflow, contact us or arrive at early so we can help you choose a suitable project to work on.
NB 2: If you will not have code to work on, you can still take advantage of the workshop, but please contact your instructor before the course.*

-   **Optional: if your data cannot be public, fake it!** We will be exchanging repositories at the end of the day, and try to reproduce each other's work. This can be problematic if your data cannot be shared. If the structure of the data can be put online, you could simulate the dataset (including covariates, so simple models have similar outcomes) using a package like [`synthpop`](https://cran.r-project.org/web/packages/synthpop/index.html), which simulates fake data within the same structure. Or check out [this post on conjurer](https://www.r-bloggers.com/generate-synthetic-data-using-r/) or [this paper on synthesizing data](https://doi.org/10.3390/psych3040045).
