---
format: "html"
---

# Welcome!

Writing code that works is one thing. Writing code that is clear, reusable, and easy to maintain is another.

In research and data analysis, it’s not enough to get results once. Your code should be structured in a way that allows you—and others—to understand it, reuse it, and confidently run it again in the future. Good coding practices are what make the difference.

In this workshop, you’ll learn how to write clean, readable, and reusable code. We’ll cover practical best practices such as organizing your projects effectively, structuring scripts and functions logically, writing meaningful comments, and documenting your work so it remains understandable over time.

We’ll also introduce tools like Git and GitHub to help you manage changes, collaborate efficiently, and keep your code under control.

Developing good habits may take a little extra effort at first—but it will save you time, reduce errors, and make your work more professional and sustainable in the long run.

Let’s move from code that just works to code that works well.

Our workshop material is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/). You can [view the license here](https://github.com/UtrechtUniversity/workshop-computational-reproducibility/blob/main/LICENSE.md).
