name: Check Markdown links

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .markdown_link_check.json
        file-extension: .qmd
